### PR TITLE
fix: Sync basename parsing for different hosts

### LINKED ISSUE #457: 🐛 Sync doesn't appear to work
### Description

Trying to sync videos. The toast message appears but disappears. Looking in synced items shows the files but states "Not found". Nothing is appearing in logs at all.

### Reproduction steps

```bash
1. Go to any library item
2. Click on sync
```

### Screenshots

_No response_

### Logs

```bash
Nothing appears in logs
```

### Platform

Android

### App Version

v0.7.5

### PR DESCRIPTION
**Pull request by benjamin-stern**
## Pull Request Description

I tested the latest release of 8.0 and saw that this issue still hasn't been resolved, so I thought I would take a whirl at it.

Fixes the issue with malformed filename where it seems there are slashes in the file's name, this sanitizes it if for some reason it has occurred.

It updates and persists the name and includes it in the download task.

I've tested and confirmed the fix on the windows development build (unfortunately I don't have the environment setup to test android)

## Issue Being Fixed

This fixes the issues where the files cannot be synced for some users.

Resolves #457 #451

## Checklist

- [ ] If a new package was added, did you ensure it works for all supported platforms? Is the package well maintained
- [ ] Check that any changes are related to the issue at hand.

### CODE REVIEW

**Comment by aero31aero** [comment]
The code looks good, but I have a question. In the issue, the file name I was failing to sync didn't have forward slashes in it.. how does it change the situation there?

(Also, I'm a noob at Flutter, is there an easy way for me to test this PR locally and report back?)

**Comment by benjamin-stern** [comment]
@aero31aero I'm not sure what systems you are running on but I suspect if you have the issue on one client you'll probably have it on all clients. For me personally I have the issue with Android and Windows so I developed and tested on my windows machine.

[Windows Build](https://drive.google.com/file/d/1xIEI5JuO6xBcRPWSS8eJvklWAr8qjdEs/view?usp=sharing)

You can click on the above link to download the windows build and test that it functions correctly. (works for me)

I suspect it's cause by my Jellyfin Server being installed on a windows machine and so it retrieves the path as part of the file location and tries to nest it internally, instead i just tell it to get the filename and strip out any `\` characters if they remain and make that the file and path local when downloading and saving.

File: lib/providers/sync_provider.dart [hunk 1]
```diff
@@ -503,11 +503,19 @@ class SyncNotifier extends StateNotifier<SyncSettingsModel> {
         await ref.read(backgroundDownloaderProvider).cancelTaskWithId(currentTask.id);
       }
       if (!skipDownload) {
+        // Sanitize filename to avoid path separators causing ArgumentError.
+        final rawFilename = syncItem.videoFileName;
+        final safeFilename = path.basename(rawFilename ?? 'unknown').replaceAll(RegExp(r'[\\/]+'), '_');
+        if (safeFilename != rawFilename) {
+          // Update syncItem expectation so completion detection (videoFile.existsSync) matches saved file.
+          syncItem = syncItem.copyWith(videoFileName: safeFilename);
+          await updateItem(syncItem); // persist new filename
```
Comment (PartyDonut) [inline lib/providers/sync_provider.dart]: Instead of sanitizing the name here and only when downloading. It would be better to always sanitize it inside of the "createSyncItem" function. That way we don't loose the file reference for any reason.

Also please don't use comments when it's clear what is happening. Create a new extension function in string_extensions.dart and give it a suitable name.

**Review by PartyDonut — CHANGES_REQUESTED** [review]

**Comment by PartyDonut** [comment]
First of thanks for implementing this 👍🏼 .

While sanitizing the file is a good thing, like @aero31aero mentioned I'm also not quite sure this fixes the issues some people where having. 

So let's merge it after the requested changes. But will probably have to check in with the issue creator whether this fixes it for them.

**Comment by benjamin-stern** [comment]
@PartyDonut right part of the benefit is that I was also experiencing the bug on all my clients both windows/android (multiple clients), although I only built and tested for windows i expect the fix to affect all clients positively.

As requested I moved the functionality to the string extensions and I've found that it works like the path.basename but support non-linux type servers and since I was running jellyfin on a windows server now the download function appears to work as expected.

It would be great to hear feedback from others that it's working as expected (including for iOS platforms) I will test the android when it's merged.

Thank you for your attention to the matter in trying to help resolve.
🙏

File: lib/providers/sync_provider.dart (hunk 1 above)
Comment (benjamin-stern) [reply lib/providers/sync_provider.dart]: Done
