### PR TITLE
fix: Playback speed shortcuts and reset speed on new video

### LINKED ISSUE #795: 🐛 Keyboard shortcuts for Play/Pause and Volume do not work when launching the player
### Description

When launching the player and navigating using only the keyboard, the keys for Play/Pause and volume control do not work.

**Additional information**

If the following line is commented out:

https://github.com/DonutWare/Fladder/blob/133a00f7f74235d0491a7cbcc3e4a4fc2e2b6aa3/lib/util/input_handler.dart#L75

the player starts reacting to Play/Pause and volume keys as expected.

### Reproduction steps

```bash
1. Go to the show using only the keyboard
2. Start watching by press Enter key
3. Try press Arrow Up/Arrow Down to adjust the volume
4. Try press Space to toggle Play/Pause
```

### Screenshots

_No response_

### Logs

```bash

```

### Platform

Linux

### App Version

v0.10.1

### Jellyfin server

10.11.6 on docker

### PR DESCRIPTION
**Pull request by Julien9969**
## Pull Request Description

- Fix keyboard shortcuts crtl + up for speed up not working
- Reset playbackRateProvider to 1.0 when loading a new playback item to prevent stale speed UI values
- Remove manual focusNode.requestFocus() that conflicted with autofocus, fixing keyboard-only navigation
- Fix PathAccessException crash in sync provider temp file cleanup on Windows

## Issue Being Fixed
#795 
## Checklist

- [ ] If a new package was added, did you ensure it works for all supported platforms? Is the package well maintained
- [ ] Check that any changes are related to the issue at hand.

### CODE REVIEW

File: lib/providers/sync_provider.dart [hunk 1]
```diff
@@ -153,14 +153,19 @@ class SyncNotifier extends StateNotifier<SyncSettingsModel> {
...
         if (file is File) {
           final fileName = file.path.split(Platform.pathSeparator).last;
-          final fileSize = await file.length();
-          if (fileName.startsWith('com.bbflight.background_downloader') && fileSize != 0) {
-            try {
-              await file.delete();
-              log('Deleted temporary file: $fileName from ${dir.path}');
-            } catch (e) {
-              log('Failed to delete file $fileName: $e');
+          try {
```
Comment (PartyDonut) [inline lib/providers/sync_provider.dart]: This should probably be in a different pull request?

Comment (Julien9969) [reply lib/providers/sync_provider.dart]: done
