### PR TITLE
fix: Parsing non-ascii domains

### LINKED ISSUE #640: 🐛 Valid Domain Unable to Connect
### Description

When trying to add a valid domain ending in `.みんな`, the app is unable to connect and infinitely loads. However, replacing the domain with `xn--q9jyb4c`, the app is able to connect.

Reproduced on web and Android.

### Reproduction steps

```bash
1. Connect to an instance with domain ending in `.みんな`
2. Click "Log in"
3. Connect button will display the loading icon indefinitely
```

### Screenshots

_No response_

### Logs

```bash
main.dart.js:7314  Uncaught Error
    at Object.o (main.dart.js:4338:20)
    at main.dart.js:187336:15
    at cMX.a (main.dart.js:5726:63)
    at cMX.$2 (main.dart.js:78940:14)
    at cKC.$1 (main.dart.js:78934:21)
    at aiX.Fp (main.dart.js:80356:33)
    at ckB.$0 (main.dart.js:79469:11)
    at Object.PX (main.dart.js:5897:40)
    at ah.Jp (main.dart.js:79387:3)
    at ckt.$0 (main.dart.js:79432:13)
main.dart.js:7314  Uncaught Error
main.dart.js:7314  Uncaught Error
    at Object.o (main.dart.js:4338:20)
    at Object.kY (main.dart.js:8219:18)
    at main.dart.js:126417:5
    at cMX.a (main.dart.js:5726:63)
    at cMX.$2 (main.dart.js:78940:14)
    at cKC.$1 (main.dart.js:78934:21)
    at aiX.Fp (main.dart.js:80356:33)
    at ckB.$0 (main.dart.js:79469:11)
    at Object.PX (main.dart.js:5897:40)
    at ah.Jp (main.dart.js:79387:3)
```

### Platform

Web, Android

### App Version

Latest

### Jellyfin server

10.11.3 on Docker

### PR DESCRIPTION
**Pull request by kikibase**
- added puny coder dependency
-  non-ascii domains can now be resolved

## Pull Request Description

just changed api_provider.dart to use punycoder to encode non-ascii characters in domain names

## Issue Being Fixed

Resolves #640

## Screenshots / Recordings

no visual change

## Checklist

- [x] If a new package was added, did you ensure it works for all supported platforms? Is the package well maintained
- [x] Check that any changes are related to the issue at hand.

### CODE REVIEW

File: lib/providers/api_provider.dart [hunk 1]
```diff
@@ -54,14 +56,25 @@ class JellyRequest implements Interceptor {
...
     final connectivityNotifier = ref.read(connectivityStatusProvider.notifier);
-    final serverUrl = ref.read(serverUrlProvider);
-    try {
-      if (serverUrl?.isEmpty == true || serverUrl == null) throw const HttpException("Failed to connect");
+    String? serverUrl = ref.read(serverUrlProvider);
 
+    try {
+      if (serverUrl?.isEmpty == true || serverUrl == null)
+        throw const HttpException("Failed to connect");
+      //host needs to be separated as punycodec breaks if its given any extras / or other characters
```
Comment (PartyDonut) [inline lib/providers/api_provider.dart]: Let's move this to either the normalizeUrl function. Or create a second function that properly decodes a url and call that inside of the serverUrlProvider.

This only fixes the api calls. But any url string constructions will not use the PunnycodeCodec.

File: lib/providers/api_provider.dart [hunk 2]
```diff
@@ -54,14 +56,25 @@ class JellyRequest implements Interceptor {
...
+      int? port = Uri.parse(serverUrl).port;
+      String scheme = Uri.parse(serverUrl).scheme;
+      String? host = serverUrl.replaceAll(
+          RegExp(r'^(https?://)|(:\d+)|(/)'), ''); //removes scheme and port
+      String decodedhost = const PunycodeCodec().encode(host);
+      serverUrl = "$scheme://$decodedhost:$port";
+      print(serverUrl);
```
Comment (PartyDonut) [inline lib/providers/api_provider.dart]: We probably don't want to print at every request. Would make for a messy log.

File: pubspec.yaml [hunk 3]
```diff
@@ -132,6 +132,7 @@ dependencies:
   dart_mappable: ^4.6.0
   flutter_native_splash: ^2.4.7
   macos_window_utils: ^1.9.0
+  punycoder: ^0.2.2
```
Comment (PartyDonut) [inline pubspec.yaml]: I'm not sure should we sort this under `# Network and HTTP` or is it not really related to just Networking/HTTP?

It's fine to leave it in `# Other`

File: lib/providers/api_provider.dart (hunk 2 above)
Comment (kikibase) [reply lib/providers/api_provider.dart]: oh sorry forgot to remove that while debugging will work on those

File: lib/providers/api_provider.dart (hunk 1 above)
Comment (kikibase) [reply lib/providers/api_provider.dart]: i've moved it over to normalizeUrl and also added one change to allow custom path urls. Tested for 4 different cases and everything was working

**Comment by kikibase** [comment]
I decided to also check issue #641 it was a really small fix so i decided to just add it to this pull request if that's fine.
Update: this did not fix the issue after further testing

File: lib/main.dart [hunk 4]
```diff
@@ -336,7 +336,7 @@ class _MainState extends ConsumerState<Main> with WindowListener, WidgetsBinding
                 return locale;
               }
               final matchByLanguage = supportedLocales.firstWhere(
-                (l) => l.languageCode == locale.languageCode,
+                (l) => l == locale,
```
Comment (PartyDonut) [inline lib/main.dart]: This also breaks locales that don't exactly match the translation file in weblate.
It might be a incorrect set-up on my end but the original was implemented to match similar languages So not sure if this would work correctly.

**Comment by PartyDonut** [comment]
Thanks for fixing this!
